### ISSUE TITLE
创建docs目录

### ISSUE THREAD

**Issue by haozihhr** [haozihhr/haozihhr.github.io#1]
不然无法查看文件，但是我手机，所以不能创建文件夹

**Comment by SadEPa0628** [comment]
![image](https://github.com/haozihhr/haozihhr.github.io/assets/120295331/77832353-21df-41fa-b6b5-3e5bb37de176)

**Comment by SadEPa0628** [comment]
ChatGPT（GPT-3.5）：
为了优化这些代码，可以考虑以下几个方面：

1. 使用 HTTPS 进行资源加载：将 index.html 和 docs.php 中使用的资源链接中的 "http://" 替换为 "https://"，以确保使用安全的加密连接加载资源。

2. 将外部 CSS 和 JavaScript 库使用本地文件引入：可以下载所需的 CSS 和 JavaScript 文件，将它们存储在本地服务器上，并使用相对路径进行引用，而不是依赖外部链接。这样可以减少对外部资源的依赖，提高加载速度，并确保资源可用性。

3. 使用版本稳定的资源链接：确保所使用的第三方库的链接指向稳定的版本，而不是特定的版本号。这样可以避免在将来库的更新时出现意外的兼容性问题。

4. 将 PHP 文件中的代码逻辑进行整理和优化：对于 docs.php 文件中的 PHP 代码，可以进行代码逻辑的整理和优化，以提高可读性和性能。以下是一些建议：

- 使用恰当的变量命名：选择具有描述性的变量名，以提高代码的可读性。

- 使用函数封装重复的代码块：如果发现某些代码块在不同的地方重复使用，可以将其提取为函数，并在需要的地方进行调用。

- 避免不必要的文件系统操作：在遍历目录和文件时，尽量减少不必要的文件系统操作，例如多次调用 file_exists()。

- 避免使用全局变量：尽量避免使用全局变量，而是将数据传递给函数，以提高代码的可维护性和可测试性。

- 使用合适的错误处理机制：在代码中添加适当的错误处理机制，以便在发生错误时能够提供有用的错误信息，并采取适当的措施。

- 防止路径遍历攻击：对于从客户端传递过来的路径参数，应该进行验证和处理，以防止路径遍历攻击。

这些是一些优化代码的建议，根据具体需求和实际情况，还可以进行其他改进。

**Comment by SadEPa0628** [comment]
如果你想在手机上创建文件夹，你可以打开你的电脑，开个玩笑，以下是ChatGPT（GPT-3.5）的回答：
要在GitHub仓库上创建一个文件夹，你需要使用GitHub的Web界面进行操作，而不是使用Git命令。下面是在GitHub上创建文件夹的步骤：

1. 打开GitHub网站并登录到你的账户。
2. 导航到你想要创建文件夹的仓库页面。
3. 在仓库页面上方，你会看到一个绿色的按钮，上面写着"Add file"（添加文件）。点击这个按钮，然后从下拉菜单中选择"Create new file"（创建新文件）。

4. 在文件名输入框中，输入文件夹的名称，确保在文件名后面加上一个斜杠（/），这将告诉GitHub你正在创建一个文件夹。例如，如果你想要创建一个名为"文件夹"的文件夹，你应该输入"文件夹/"。

5. 在文件名输入框下方的编辑框中，输入一些随意的文本，这是为了能够提交这个文件夹。你可以输入任何内容，因为在接下来的步骤中，你将删除这个文件。

6. 在页面底部的"Commit new file"（提交新文件）部分，输入一个提交消息，描述你创建文件夹的目的。

7. 最后，点击页面底部的绿色按钮"Commit new file"（提交新文件），这将创建一个空的文件夹。

现在，你已经在GitHub仓库中成功创建了一个文件夹。接下来，你可以使用Git命令或者通过GitHub网站上传文件到这个文件夹中。记得在上传文件时，指定正确的文件路径，将文件放入你刚创建的文件夹中。

**Comment by SadEPa0628** [comment]
操作演示


https://github.com/haozihhr/haozihhr.github.io/assets/120295331/5a7e1b60-de16-40f4-ab53-98bf0f0942f6

**Comment by haozihhr** [comment]
谢了
