### ISSUE TITLE
网站有两个索引

### ISSUE THREAD

**Issue by SadEPa0628** [haozihhr/haozihhr.github.io#2]
https://github.com/haozihhr/haozihhr.github.io/assets/120295331/4d59847c-4b20-4d6e-b75b-81b4b926d3e7

**Comment by haozihhr** [comment]
我无法查看视频，请将你的视频压缩一下。注意，不是打包成压缩包！

**Comment by haozihhr** [comment]
checked and you are right.它自动访问index.html，这个bug我修一下

**Comment by haozihhr** [comment]
can't fix.这个网站的目录就是我仓库的目录，不知道添加readme.md能不能修复

**Comment by haozihhr** [comment]
已修复

**Comment by SadEPa0628** [comment]
这是网页使用的索引：
![image](https://github.com/haozihhr/haozihhr.github.io/assets/120295331/c1046f21-7a2d-41e2-9df2-d467daa3c9b2)
这是正确的索引：
![image](https://github.com/haozihhr/haozihhr.github.io/assets/120295331/4e1996c6-2f31-45b9-bf9f-65550a14601a)

**Comment by haozihhr** [comment]
我这边可以正常访问，不知道是不是你的网络不好或者是你的浏览器版本不支持，这在我的手机上没有任何问题
